#!/bin/bash
PROG="slanger"
PROG_PATH="/usr/local/bin" # get this from `which slanger`
PID_PATH="/tmp"
KEY="your-app-key"
SECRET="your-app-secret"
PROG_ARGS=" --app_key $KEY --secret $SECRET"

start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
        $PROG_PATH/$PROG $PROG_ARGS & echo $! > $PID_PATH/$PROG.pid 
        echo "$PROG started"
        touch "$PID_PATH/$PROG.pid"
    fi
}

stop() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        kill $(cat $PID_PATH/$PROG.pid)
        rm "$PID_PATH/$PROG.pid"
        echo "$PROG stopped"
    else
        echo "Error! $PROG not started!" 1>&2
        exit 1
    fi
}

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac

